config/routes.rb
Codeweekend::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'users#new'
  match '/signin', :to => 'sessions#new', via: 'get' 
  match '/signup', :to => 'users#new', via: 'get' 
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/week1', :to => 'tutorials#tut1', via: 'get' 
  match '/week2', :to => 'tutorials#tut2', via: 'get' 
  match '/week3', :to => 'tutorials#tut3', via: 'get' 
  match '/week4', :to => 'tutorials#tut4', via: 'get' 
  match '/week5', :to => 'tutorials#tut5', via: 'get' 
  match '/week6', :to => 'tutorials#tut6', via: 'get' 
  match '/week7', :to => 'tutorials#tut7', via: 'get' 

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to current_user, notice: "Signed in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out, see you soon!"
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  
  before_filter :week1available, only:[:tut1]
  before_filter :week2available, only:[:tut2]
  before_filter :week3available, only:[:tut3]
  before_filter :week4available, only:[:tut4]
  before_filter :week5available, only:[:tut5]
  before_filter :week6available, only:[:tut6]
  before_filter :week7available, only:[:tut7]

  def tut1
  end

  def tut2
  end

  def tut3
  end

  def tut4
  end

  def tut5
  end

  def tut6
  end

  def tut7
  end

  private

  def week1available
    unless current_user.week1available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

  def week2available
    unless current_user.week2available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

  def week3available
    unless current_user.week3available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

  def week4available
    unless current_user.week4available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

  def week5available
    unless current_user.week5available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

  def week6available
    unless current_user.week6available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

   def week7available
    unless current_user.week7available? 
      redirect_to current_user, notice: "This week is not live yet"
    end 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
   def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id #this line essentially signs the user in after sign up
        redirect_to current_user, notice: "Thank you for signing up!"
      else
        redirect_to signup_url, error: "Uh oh, something went wrong"
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def correct_user
      redirect_to(root_url) unless current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codeweekend</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<header class="mynav">
	
	<ul>
		<% if current_user %>
		<li><%= link_to "Profile", current_user %></li>
		<li><%= link_to "Settings", edit_user_path(current_user) %></li>
		<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
	<% else %>
		<li><%= link_to "Sign In", signin_path %></li>
		<li><%= link_to "Sign Up", signup_path %></li>
		<% end %>
	</ul>
	
	</header>

	<%= yield %>

</body>
</html>

app/views/tutorials/tut1.html.erb
<div class="row">
	<p id="notice"><%= notice %></p>
	<div class="twelve columns">

		<h3 class="center_text">Title</h3><hr>
	    <section class="vertical tabs">

	    	<!-- Tabs !-->
		    <ul class="tab-nav four columns">
		    	<li class="active"><a href="#">Tab 1</a></li>
		        <li><a href="#">Tab 2</a></li>
		        <li><a href="#">Tab 3</a></li>
		    </ul>
		    <!-- Tabs !-->

		    <!-- Tab1 Section !-->		    
			<div class="tab-content eight columns active">
				<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus...</p>
			</div>
			<!-- Tab1 Section !-->

			<!-- Tab2 section !-->
			<div class="tab-content eight columns">
				<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante...</p>
			</div>
			<!-- Tab2 section !-->

			<!-- Tab3 section !-->
			<div class="tab-content eight columns">
				<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti...</p>
			</div>
			<!-- Tab3 section !-->

	    </section>

  	</div>
</div>

app/views/tutorials/tut2.html.erb
<div class="row">
	<p id="notice"><%= notice %></p>
	<div class="twelve columns">

	    <section class="vertical tabs">

	    	<!-- Tabs !-->
		    <ul class="tab-nav four columns">
		    	<li class="active"><a href="#">Tab 1</a></li>
		        <li><a href="#">Tab 2</a></li>
		        <li><a href="#">Tab 3</a></li>
		    </ul>
		    <!-- Tabs !-->

		    <!-- Tab1 Section !-->
			<div class="tab-content eight columns active">
				<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus...</p>
			</div>
			<!-- Tab1 Section !-->

			<!-- Tab2 section !-->
			<div class="tab-content eight columns">
				<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante...</p>
			</div>
			<!-- Tab2 section !-->

			<!-- Tab3 section !-->
			<div class="tab-content eight columns">
				<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti...</p>
			</div>
			<!-- Tab3 section !-->

	    </section>

  	</div>
</div>

app/views/tutorials/tut3.html.erb
<div class="row">
	<p id="notice"><%= notice %></p>
	<div class="twelve columns">

	    <section class="vertical tabs">

	    	<!-- Tabs !-->
		    <ul class="tab-nav four columns">
		    	<li class="active"><a href="#">Tab 1</a></li>
		        <li><a href="#">Tab 2</a></li>
		        <li><a href="#">Tab 3</a></li>
		    </ul>
		    <!-- Tabs !-->

		    <!-- Tab1 Section !-->
			<div class="tab-content eight columns active">
				<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus...</p>
			</div>
			<!-- Tab1 Section !-->

			<!-- Tab2 section !-->
			<div class="tab-content eight columns">
				<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante...</p>
			</div>
			<!-- Tab2 section !-->

			<!-- Tab3 section !-->
			<div class="tab-content eight columns">
				<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti...</p>
			</div>
			<!-- Tab3 section !-->

	    </section>

  	</div>
</div>

app/views/tutorials/tut4.html.erb
<div class="row">
	<p id="notice"><%= notice %></p>
	<div class="twelve columns">

	    <section class="vertical tabs">

	    	<!-- Tabs !-->
		    <ul class="tab-nav four columns">
		    	<li class="active"><a href="#">Tab 1</a></li>
		        <li><a href="#">Tab 2</a></li>
		        <li><a href="#">Tab 3</a></li>
		    </ul>
		    <!-- Tabs !-->

		    <!-- Tab1 Section !-->
			<div class="tab-content eight columns active">
				<p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus...</p>
			</div>
			<!-- Tab1 Section !-->

			<!-- Tab2 section !-->
			<div class="tab-content eight columns">
				<p>Morbi tincidunt, dui sit amet facilisis feugiat, odio metus gravida ante...</p>
			</div>
			<!-- Tab2 section !-->

			<!-- Tab3 section !-->
			<div class="tab-content eight columns">
				<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti...</p>
			</div>
			<!-- Tab3 section !-->

	    </section>

  	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "text input" %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, :class => "email input" %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password, :class => "password input" %>
  </div>
   <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => "password input" %>
  </div>
  <div class="actions">
    <div class="medium info btn"><%= f.submit %></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="centered six columns">
  	<h1>Editing user</h1>
	<%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="twelve columns">
    <h1>Listing users</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Admin</th>
          <th>Week1</th>
          <th>Week2</th>
          <th>Week3</th>
          <th>Week4</th>
          <th>Week5</th>
          <th>Week6</th>
          <th>Week7</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.admin %></td>
            <td><%= user.week1available %></td>
            <td><%= user.week2available %></td>
            <td><%= user.week3available %></td>
            <td><%= user.week4available %></td>
            <td><%= user.week5available %></td>
            <td><%= user.week6available %></td>
            <td><%= user.week7available %></td>
            
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New User', new_user_path %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="centered six columns">
	<h1>New user</h1>
	<%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="center_text" id="notice"><%= notice %></div>
		<h3 class="pull-right"><%= Time.now.strftime("%v") %></h3>
		<h3>Hello, <%= @user.name %></h3><hr class="clear">
		<h3 class="center_text">My Tutorials</h3>
	</div>
</div>

	<div class="row">

	<!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">View Project</h5>
	    <h3 class="make_white">A simple blog</h3>
	  </div>
	  <div class="procontent">
	    <p>A blog is the most basic application that can be built with rails. Mastering the skills you aquire here will go a long way in understanding rails. We will build a simple blog with an admin user capable of creating, updating and destroying posts. This tutorial will also introduce validations within models and sessions to handle authentication.</p>
	    <div class="medium primary btn pull-right"><a href="/week1">Lets Get Started</a></div>
	  </div>      
	</div>
	<!-- Project box !-->

	<!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">View Project</h5>
	    <h3 class="make_white">To-do list application</h3>
	  </div>
	  <div class="procontent">
	    <p>To-do lists keeps us organized and productive, building one is a lot of fun too. This tutorial will introduce scopes, associations between two models and go even further into authentication. The application will allow multiple users create their own todo lists and check items off as completed. Finally we will integrate twitter bootstrap for design.</p>       
	    <div class="medium primary btn pull-right"><a href="/week2">Lets Get Started</a></div>
	  </div>
	</div>
	<!-- Project box !-->

	</div>

	<div class="row">

	<!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">Coming soon</h5>
	    <h3 class="make_white">Photo blog</h3></div>
	  <div class="procontent">
	    <p>Photo sharing applications are very popular today. In this tutorial we will show you how to build one. This tutorial will implement associations between three models and file upload and storage. Once completed you should be able to create photo sharing sites as quick as you can say Cheese.</p><br>     
	    <div class="medium primary btn pull-right"><a href="/week3">Lets Get Started</a></div>
	  </div>
	  </div>
	  <!-- Project box !-->

	  <!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">Coming soon</h5>
	    <h3 class="make_white">Photo blog</h3></div>
	  <div class="procontent">
	    <p>Photo sharing applications are very popular today. In this tutorial we will show you how to build one. This tutorial will implement associations between three models and file upload and storage. Once completed you should be able to create photo sharing sites as quick as you can say Cheese.</p><br>     
	    <div class="medium primary btn pull-right"><a href="/week4">Lets Get Started</a></div>
	  </div>
	  </div>
	  <!-- Project box !-->
	</div>

	<div class="row">

	<!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">Coming soon</h5>
	    <h3 class="make_white">Photo blog</h3></div>
	  <div class="procontent">
	    <p>Photo sharing applications are very popular today. In this tutorial we will show you how to build one. This tutorial will implement associations between three models and file upload and storage. Once completed you should be able to create photo sharing sites as quick as you can say Cheese.</p><br>     
	    <div class="medium primary btn pull-right"><a href="/week5">Lets Get Started</a></div>
	  </div>
	  </div>
	  <!-- Project box !-->

	  <!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">Coming soon</h5>
	    <h3 class="make_white">Photo blog</h3></div>
	  <div class="procontent">
	    <p>Photo sharing applications are very popular today. In this tutorial we will show you how to build one. This tutorial will implement associations between three models and file upload and storage. Once completed you should be able to create photo sharing sites as quick as you can say Cheese.</p><br>     
	    <div class="medium primary btn pull-right"><a href="/week6">Lets Get Started</a></div>
	  </div>
	  </div>
	  <!-- Project box !-->
	</div>

	<div class="row">

	<!-- Project box !-->
	<div class="six columns projectsec">
	  <div class="protitle">
	    <h5 class="pull-right">Coming soon</h5>
	    <h3 class="make_white">Photo blog</h3></div>
	  <div class="procontent">
	    <p>Photo sharing applications are very popular today. In this tutorial we will show you how to build one. This tutorial will implement associations between three models and file upload and storage. Once completed you should be able to create photo sharing sites as quick as you can say Cheese.</p><br>     
	    <div class="medium primary btn pull-right"><a href="/week7">Lets Get Started</a></div>
	  </div>
	  </div>
	  <!-- Project box !-->
	</div>

	<br><br><br><br>